"""
CurveTracker API
----------------
A unified interface for other scripts to access CurveTracker data and configuration.

This module provides two main ways to interact with CurveTracker:
1. Data Access (Cached): Read the latest generated JSON data (fast, no API calls)
2. Live Data (Direct): Fetch real-time data using the CurveTracker engine
3. Management: Manage the pool configuration

Usage:
    from curve_tracker_api import CurveDataAPI

    # 1. Read cached data (generated by cron/export)
    api = CurveDataAPI()
    pools = api.get_pools(chain="ethereum")
    
    for pool in pools:
        print(f"{pool['name']}: {pool['latest']['total_apy']}% APY")

    # 2. Fetch live data (slower, hits APIs)
    live_data = api.fetch_live_pool_data("ethereum", "0x...")
"""

import json
import os
import sys
from typing import Dict, List, Optional, Union, Any
from dataclasses import asdict

# Ensure local imports work
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from pool_manager import PoolManager
from curve_tracker import CurveTracker, PoolData


class CurveDataAPI:
    """
    Main API class for accessing CurveTracker data.
    """
    
    def __init__(self, data_dir: str = "data", config_file: str = "pools.json"):
        """
        Initialize the API.
        
        Args:
            data_dir: Directory where JSON exports are stored
            config_file: Path to the pools configuration file
        """
        self.data_dir = data_dir
        self.config_file = config_file
        self._manager = PoolManager(config_file)
        self._tracker = None  # Lazy init
        
    # ==========================================
    # Cached Data Access (Read JSONs)
    # ==========================================
    
    def get_latest_data_file_path(self) -> str:
        """Get path to the latest data JSON file"""
        return os.path.join(self.data_dir, "curve_pools_latest.json")

    def load_latest_data(self) -> Dict[str, Any]:
        """
        Load the full content of curve_pools_latest.json.
        
        Returns:
            Dictionary containing 'metadata' and 'pools'
        """
        filepath = self.get_latest_data_file_path()
        if not os.path.exists(filepath):
            print(f"⚠️  Warning: Data file not found at {filepath}")
            return {"metadata": {}, "pools": []}
            
        try:
            with open(filepath, 'r') as f:
                return json.load(f)
        except json.JSONDecodeError as e:
            print(f"❌ Error decoding JSON: {e}")
            return {"metadata": {}, "pools": []}

    def get_pools(self, chain: Optional[str] = None) -> List[Dict[str, Any]]:
        """
        Get all pools from the cached data, optionally filtered by chain.
        
        Args:
            chain: Filter by chain name (case-insensitive)
            
        Returns:
            List of pool dictionaries
        """
        data = self.load_latest_data()
        pools = data.get("pools", [])
        
        if chain:
            chain_lower = chain.lower()
            return [p for p in pools if p.get("chain", "").lower() == chain_lower]
        
        return pools

    def get_pool_by_id(self, pool_id: str) -> Optional[Dict[str, Any]]:
        """
        Find a pool by its unique ID (e.g. 'ethereum_reusd_scrvusd').
        
        Args:
            pool_id: The unique identifier string
            
        Returns:
            Pool dictionary or None
        """
        pools = self.get_pools()
        for pool in pools:
            if pool.get("id") == pool_id:
                return pool
        return None

    def find_pool(self, identifier: str, chain: Optional[str] = None) -> Optional[Dict[str, Any]]:
        """
        Smart search for a pool by name, address, or ID.
        
        Args:
            identifier: Name, address, or ID to search for
            chain: Optional chain filter to narrow search
            
        Returns:
            Pool dictionary or None
        """
        pools = self.get_pools(chain)
        identifier_lower = identifier.lower()
        
        for pool in pools:
            # Check ID
            if pool.get("id") == identifier_lower:
                return pool
            
            # Check Name (partial match)
            if identifier_lower in pool.get("name", "").lower():
                return pool
                
            # Check Address
            if identifier_lower == pool.get("metadata", {}).get("pool_address", "").lower():
                return pool
                
        return None

    # ==========================================
    # Live Data Fetching (Use Tracker)
    # ==========================================
    
    def _get_tracker(self) -> CurveTracker:
        """Lazy load the CurveTracker instance"""
        if self._tracker is None:
            # Check global config for defaults
            config = self._manager.config
            self._tracker = CurveTracker(
                enable_stakedao=config.get("enable_stakedao", False),
                enable_beefy=config.get("enable_beefy", False),
                enable_convex=config.get("enable_convex", False)
            )
        return self._tracker

    def fetch_live_pool_data(self, chain: str, pool_address_or_name: str) -> Optional[Dict[str, Any]]:
        """
        Fetch fresh, live data for a specific pool using the CurveTracker engine.
        
        Args:
            chain: Blockchain name
            pool_address_or_name: Address or name of the pool
            
        Returns:
            Dictionary of pool data (converted from PoolData object) or None
        """
        tracker = self._get_tracker()
        
        # Look up if we have specific config for this pool to respect flags
        pool_config = self._manager.get_pool(chain, pool_address_or_name)
        
        stakedao_enabled = None
        beefy_enabled = None
        convex_enabled = None

        if pool_config:
            stakedao_enabled = pool_config.get("stakedao_enabled")
            beefy_enabled = pool_config.get("beefy_enabled")
            convex_enabled = pool_config.get("convex_enabled")

        pool_data = tracker.get_pool_data(
            chain,
            pool_address_or_name,
            stakedao_enabled=stakedao_enabled,
            beefy_enabled=beefy_enabled,
            convex_enabled=convex_enabled
        )
        
        if pool_data:
            return asdict(pool_data)
        return None

    # ==========================================
    # Configuration Management
    # ==========================================
    
    def add_pool_to_tracking(self, chain: str, pool: str, **kwargs) -> bool:
        """
        Add a pool to the configuration file.
        
        Args:
            chain: Blockchain name
            pool: Address
            **kwargs: Additional args like comment, stakedao_enabled, etc.
        
        Returns:
            True if successful
        """
        return self._manager.add_pool(chain, pool, **kwargs)

    def remove_pool_from_tracking(self, chain: str, pool: str) -> bool:
        """Remove a pool from configuration."""
        return self._manager.remove_pool(chain, pool)

    def list_tracked_pools(self) -> List[Dict]:
        """List all pools currently in configuration."""
        return self._manager.list_pools()
